//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Indigo.CardReq {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Request", Namespace="http://schemas.veneka.com/Indigo")]
    [System.SerializableAttribute()]
    public partial class Request : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int AccountTypeField;
        
        private string BranchCodeField;
        
        private int CardIssueMethodIdField;
        
        private int CardIssueTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long CmsIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContractNumberField;
        
        private string CurrencyCodeField;
        
        private string CustomerAccountNumberField;
        
        private string CustomerFirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerIdField;
        
        private string CustomerLastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerMiddleNameField;
        
        private int CustomerTitleField;
        
        private int CustomerTypeField;
        
        private string DomicileBranchCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdNumberField;
        
        private string IssuerCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameOnCardField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostalAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrintingBranchCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PriorityField;
        
        private string ProductCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequestBranchCodeField;
        
        private int RequestChannelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequestReferenceNumberField;
        
        private int ResidencyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int AccountType {
            get {
                return this.AccountTypeField;
            }
            set {
                if ((this.AccountTypeField.Equals(value) != true)) {
                    this.AccountTypeField = value;
                    this.RaisePropertyChanged("AccountType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string BranchCode {
            get {
                return this.BranchCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.BranchCodeField, value) != true)) {
                    this.BranchCodeField = value;
                    this.RaisePropertyChanged("BranchCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CardIssueMethodId {
            get {
                return this.CardIssueMethodIdField;
            }
            set {
                if ((this.CardIssueMethodIdField.Equals(value) != true)) {
                    this.CardIssueMethodIdField = value;
                    this.RaisePropertyChanged("CardIssueMethodId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CardIssueType {
            get {
                return this.CardIssueTypeField;
            }
            set {
                if ((this.CardIssueTypeField.Equals(value) != true)) {
                    this.CardIssueTypeField = value;
                    this.RaisePropertyChanged("CardIssueType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long CmsId {
            get {
                return this.CmsIdField;
            }
            set {
                if ((this.CmsIdField.Equals(value) != true)) {
                    this.CmsIdField = value;
                    this.RaisePropertyChanged("CmsId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactNumber {
            get {
                return this.ContactNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactNumberField, value) != true)) {
                    this.ContactNumberField = value;
                    this.RaisePropertyChanged("ContactNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContractNumber {
            get {
                return this.ContractNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ContractNumberField, value) != true)) {
                    this.ContractNumberField = value;
                    this.RaisePropertyChanged("ContractNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CurrencyCode {
            get {
                return this.CurrencyCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrencyCodeField, value) != true)) {
                    this.CurrencyCodeField = value;
                    this.RaisePropertyChanged("CurrencyCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CustomerAccountNumber {
            get {
                return this.CustomerAccountNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerAccountNumberField, value) != true)) {
                    this.CustomerAccountNumberField = value;
                    this.RaisePropertyChanged("CustomerAccountNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CustomerFirstName {
            get {
                return this.CustomerFirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerFirstNameField, value) != true)) {
                    this.CustomerFirstNameField = value;
                    this.RaisePropertyChanged("CustomerFirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerId {
            get {
                return this.CustomerIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerIdField, value) != true)) {
                    this.CustomerIdField = value;
                    this.RaisePropertyChanged("CustomerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CustomerLastName {
            get {
                return this.CustomerLastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerLastNameField, value) != true)) {
                    this.CustomerLastNameField = value;
                    this.RaisePropertyChanged("CustomerLastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerMiddleName {
            get {
                return this.CustomerMiddleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerMiddleNameField, value) != true)) {
                    this.CustomerMiddleNameField = value;
                    this.RaisePropertyChanged("CustomerMiddleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CustomerTitle {
            get {
                return this.CustomerTitleField;
            }
            set {
                if ((this.CustomerTitleField.Equals(value) != true)) {
                    this.CustomerTitleField = value;
                    this.RaisePropertyChanged("CustomerTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CustomerType {
            get {
                return this.CustomerTypeField;
            }
            set {
                if ((this.CustomerTypeField.Equals(value) != true)) {
                    this.CustomerTypeField = value;
                    this.RaisePropertyChanged("CustomerType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string DomicileBranchCode {
            get {
                return this.DomicileBranchCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.DomicileBranchCodeField, value) != true)) {
                    this.DomicileBranchCodeField = value;
                    this.RaisePropertyChanged("DomicileBranchCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailAddress {
            get {
                return this.EmailAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailAddressField, value) != true)) {
                    this.EmailAddressField = value;
                    this.RaisePropertyChanged("EmailAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdNumber {
            get {
                return this.IdNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.IdNumberField, value) != true)) {
                    this.IdNumberField = value;
                    this.RaisePropertyChanged("IdNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string IssuerCode {
            get {
                return this.IssuerCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.IssuerCodeField, value) != true)) {
                    this.IssuerCodeField = value;
                    this.RaisePropertyChanged("IssuerCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NameOnCard {
            get {
                return this.NameOnCardField;
            }
            set {
                if ((object.ReferenceEquals(this.NameOnCardField, value) != true)) {
                    this.NameOnCardField = value;
                    this.RaisePropertyChanged("NameOnCard");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostalAddress {
            get {
                return this.PostalAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.PostalAddressField, value) != true)) {
                    this.PostalAddressField = value;
                    this.RaisePropertyChanged("PostalAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrintingBranchCode {
            get {
                return this.PrintingBranchCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PrintingBranchCodeField, value) != true)) {
                    this.PrintingBranchCodeField = value;
                    this.RaisePropertyChanged("PrintingBranchCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Priority {
            get {
                return this.PriorityField;
            }
            set {
                if ((this.PriorityField.Equals(value) != true)) {
                    this.PriorityField = value;
                    this.RaisePropertyChanged("Priority");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ProductCode {
            get {
                return this.ProductCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductCodeField, value) != true)) {
                    this.ProductCodeField = value;
                    this.RaisePropertyChanged("ProductCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RequestBranchCode {
            get {
                return this.RequestBranchCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestBranchCodeField, value) != true)) {
                    this.RequestBranchCodeField = value;
                    this.RaisePropertyChanged("RequestBranchCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int RequestChannel {
            get {
                return this.RequestChannelField;
            }
            set {
                if ((this.RequestChannelField.Equals(value) != true)) {
                    this.RequestChannelField = value;
                    this.RaisePropertyChanged("RequestChannel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RequestReferenceNumber {
            get {
                return this.RequestReferenceNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestReferenceNumberField, value) != true)) {
                    this.RequestReferenceNumberField = value;
                    this.RaisePropertyChanged("RequestReferenceNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Residency {
            get {
                return this.ResidencyField;
            }
            set {
                if ((this.ResidencyField.Equals(value) != true)) {
                    this.ResidencyField = value;
                    this.RaisePropertyChanged("Residency");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseResponse", Namespace="http://schemas.veneka.com/Indigo")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Indigo.CardReq.Response))]
    public partial class BaseResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseExceptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseMessageField;
        
        private Indigo.CardReq.ResponseCode ResponseTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseException {
            get {
                return this.ResponseExceptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseExceptionField, value) != true)) {
                    this.ResponseExceptionField = value;
                    this.RaisePropertyChanged("ResponseException");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseMessage {
            get {
                return this.ResponseMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseMessageField, value) != true)) {
                    this.ResponseMessageField = value;
                    this.RaisePropertyChanged("ResponseMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Indigo.CardReq.ResponseCode ResponseType {
            get {
                return this.ResponseTypeField;
            }
            set {
                if ((this.ResponseTypeField.Equals(value) != true)) {
                    this.ResponseTypeField = value;
                    this.RaisePropertyChanged("ResponseType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Response", Namespace="http://schemas.veneka.com/Indigo")]
    [System.SerializableAttribute()]
    public partial class Response : Indigo.CardReq.BaseResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseCode", Namespace="http://schemas.veneka.com/Indigo")]
    public enum ResponseCode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute(Value="00")]
        _00 = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute(Value="01")]
        _01 = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute(Value="02")]
        _02 = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute(Value="03")]
        _03 = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute(Value="04")]
        _04 = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CardStatus", Namespace="http://schemas.datacontract.org/2004/07/IndigoCardIssuanceService.util")]
    public enum CardStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ACTIVATE = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DEACTIVATE = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        STOP_CARD = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CardManagementResponse", Namespace="http://schemas.datacontract.org/2004/07/Veneka.Indigo.ServicesCardManagement.API." +
        "DataContracts")]
    [System.SerializableAttribute()]
    public partial class CardManagementResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Indigo.CardReq.AWBDetails AWBDetailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Indigo.CardReq.ReceipientDetails RecipientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Indigo.CardReq.AWBDetails AWBDetail {
            get {
                return this.AWBDetailField;
            }
            set {
                if ((object.ReferenceEquals(this.AWBDetailField, value) != true)) {
                    this.AWBDetailField = value;
                    this.RaisePropertyChanged("AWBDetail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Indigo.CardReq.ReceipientDetails Recipient {
            get {
                return this.RecipientField;
            }
            set {
                if ((object.ReferenceEquals(this.RecipientField, value) != true)) {
                    this.RecipientField = value;
                    this.RaisePropertyChanged("Recipient");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseCode {
            get {
                return this.ResponseCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseCodeField, value) != true)) {
                    this.ResponseCodeField = value;
                    this.RaisePropertyChanged("ResponseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseMessage {
            get {
                return this.ResponseMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseMessageField, value) != true)) {
                    this.ResponseMessageField = value;
                    this.RaisePropertyChanged("ResponseMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AWBDetails", Namespace="http://schemas.datacontract.org/2004/07/Veneka.Indigo.ServicesCardManagement.API." +
        "DataContracts")]
    [System.SerializableAttribute()]
    public partial class AWBDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AWBRefField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardReferenceNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerNamesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaskedCardNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AWBRef {
            get {
                return this.AWBRefField;
            }
            set {
                if ((object.ReferenceEquals(this.AWBRefField, value) != true)) {
                    this.AWBRefField = value;
                    this.RaisePropertyChanged("AWBRef");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardReferenceNumber {
            get {
                return this.CardReferenceNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CardReferenceNumberField, value) != true)) {
                    this.CardReferenceNumberField = value;
                    this.RaisePropertyChanged("CardReferenceNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactNumber {
            get {
                return this.ContactNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactNumberField, value) != true)) {
                    this.ContactNumberField = value;
                    this.RaisePropertyChanged("ContactNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerNames {
            get {
                return this.CustomerNamesField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerNamesField, value) != true)) {
                    this.CustomerNamesField = value;
                    this.RaisePropertyChanged("CustomerNames");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerTitle {
            get {
                return this.CustomerTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerTitleField, value) != true)) {
                    this.CustomerTitleField = value;
                    this.RaisePropertyChanged("CustomerTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaskedCardNumber {
            get {
                return this.MaskedCardNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.MaskedCardNumberField, value) != true)) {
                    this.MaskedCardNumberField = value;
                    this.RaisePropertyChanged("MaskedCardNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReceipientDetails", Namespace="http://schemas.datacontract.org/2004/07/Veneka.Indigo.ServicesCardManagement.API." +
        "DataContracts")]
    [System.SerializableAttribute()]
    public partial class ReceipientDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDnumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NamesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactNumber {
            get {
                return this.ContactNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactNumberField, value) != true)) {
                    this.ContactNumberField = value;
                    this.RaisePropertyChanged("ContactNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IDnumber {
            get {
                return this.IDnumberField;
            }
            set {
                if ((object.ReferenceEquals(this.IDnumberField, value) != true)) {
                    this.IDnumberField = value;
                    this.RaisePropertyChanged("IDnumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Names {
            get {
                return this.NamesField;
            }
            set {
                if ((object.ReferenceEquals(this.NamesField, value) != true)) {
                    this.NamesField = value;
                    this.RaisePropertyChanged("Names");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.veneka.com/Indigo", ConfigurationName="CardReq.ICardRequest")]
    public interface ICardRequest {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.veneka.com/Indigo/ICardRequest/RequestCard", ReplyAction="http://schemas.veneka.com/Indigo/ICardRequest/RequestCardResponse")]
        Indigo.CardReq.Response RequestCard(Indigo.CardReq.Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.veneka.com/Indigo/ICardRequest/RequestCard", ReplyAction="http://schemas.veneka.com/Indigo/ICardRequest/RequestCardResponse")]
        System.Threading.Tasks.Task<Indigo.CardReq.Response> RequestCardAsync(Indigo.CardReq.Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.veneka.com/Indigo/ICardRequest/RequestCardExt", ReplyAction="http://schemas.veneka.com/Indigo/ICardRequest/RequestCardExtResponse")]
        Indigo.CardReq.Response RequestCardExt(Indigo.CardReq.Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.veneka.com/Indigo/ICardRequest/RequestCardExt", ReplyAction="http://schemas.veneka.com/Indigo/ICardRequest/RequestCardExtResponse")]
        System.Threading.Tasks.Task<Indigo.CardReq.Response> RequestCardExtAsync(Indigo.CardReq.Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.veneka.com/Indigo/ICardRequest/RequestedCardStatus", ReplyAction="http://schemas.veneka.com/Indigo/ICardRequest/RequestedCardStatusResponse")]
        Indigo.CardReq.Response RequestedCardStatus(string referenceNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.veneka.com/Indigo/ICardRequest/RequestedCardStatus", ReplyAction="http://schemas.veneka.com/Indigo/ICardRequest/RequestedCardStatusResponse")]
        System.Threading.Tasks.Task<Indigo.CardReq.Response> RequestedCardStatusAsync(string referenceNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.veneka.com/Indigo/ICardRequest/QueryCardRequest", ReplyAction="http://schemas.veneka.com/Indigo/ICardRequest/QueryCardRequestResponse")]
        Indigo.CardReq.Response QueryCardRequest(string referenceNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.veneka.com/Indigo/ICardRequest/QueryCardRequest", ReplyAction="http://schemas.veneka.com/Indigo/ICardRequest/QueryCardRequestResponse")]
        System.Threading.Tasks.Task<Indigo.CardReq.Response> QueryCardRequestAsync(string referenceNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.veneka.com/Indigo/ICardRequest/ActivateCard", ReplyAction="http://schemas.veneka.com/Indigo/ICardRequest/ActivateCardResponse")]
        Indigo.CardReq.Response ActivateCard(string referenceNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.veneka.com/Indigo/ICardRequest/ActivateCard", ReplyAction="http://schemas.veneka.com/Indigo/ICardRequest/ActivateCardResponse")]
        System.Threading.Tasks.Task<Indigo.CardReq.Response> ActivateCardAsync(string referenceNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.veneka.com/Indigo/ICardRequest/ChangeCardStatus", ReplyAction="http://schemas.veneka.com/Indigo/ICardRequest/ChangeCardStatusResponse")]
        Indigo.CardReq.Response ChangeCardStatus(string cardReferenceNumber, Indigo.CardReq.CardStatus newStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.veneka.com/Indigo/ICardRequest/ChangeCardStatus", ReplyAction="http://schemas.veneka.com/Indigo/ICardRequest/ChangeCardStatusResponse")]
        System.Threading.Tasks.Task<Indigo.CardReq.Response> ChangeCardStatusAsync(string cardReferenceNumber, Indigo.CardReq.CardStatus newStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.veneka.com/Indigo/ICardRequest/VerifyPersonByID", ReplyAction="http://schemas.veneka.com/Indigo/ICardRequest/VerifyPersonByIDResponse")]
        Indigo.CardReq.CardManagementResponse VerifyPersonByID(string AWBRefNumber, string IDNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.veneka.com/Indigo/ICardRequest/VerifyPersonByID", ReplyAction="http://schemas.veneka.com/Indigo/ICardRequest/VerifyPersonByIDResponse")]
        System.Threading.Tasks.Task<Indigo.CardReq.CardManagementResponse> VerifyPersonByIDAsync(string AWBRefNumber, string IDNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.veneka.com/Indigo/ICardRequest/QueryCardByAWBNumber", ReplyAction="http://schemas.veneka.com/Indigo/ICardRequest/QueryCardByAWBNumberResponse")]
        Indigo.CardReq.CardManagementResponse QueryCardByAWBNumber(string AWBRefNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.veneka.com/Indigo/ICardRequest/QueryCardByAWBNumber", ReplyAction="http://schemas.veneka.com/Indigo/ICardRequest/QueryCardByAWBNumberResponse")]
        System.Threading.Tasks.Task<Indigo.CardReq.CardManagementResponse> QueryCardByAWBNumberAsync(string AWBRefNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.veneka.com/Indigo/ICardRequest/GetCardbyContactNumber", ReplyAction="http://schemas.veneka.com/Indigo/ICardRequest/GetCardbyContactNumberResponse")]
        Indigo.CardReq.Response GetCardbyContactNumber(string phoneNumber, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.veneka.com/Indigo/ICardRequest/GetCardbyContactNumber", ReplyAction="http://schemas.veneka.com/Indigo/ICardRequest/GetCardbyContactNumberResponse")]
        System.Threading.Tasks.Task<Indigo.CardReq.Response> GetCardbyContactNumberAsync(string phoneNumber, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.veneka.com/Indigo/ICardRequest/GetCardbyContactNumberExt", ReplyAction="http://schemas.veneka.com/Indigo/ICardRequest/GetCardbyContactNumberExtResponse")]
        Indigo.CardReq.Response GetCardbyContactNumberExt(string phoneNumber, string last4Digits, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.veneka.com/Indigo/ICardRequest/GetCardbyContactNumberExt", ReplyAction="http://schemas.veneka.com/Indigo/ICardRequest/GetCardbyContactNumberExtResponse")]
        System.Threading.Tasks.Task<Indigo.CardReq.Response> GetCardbyContactNumberExtAsync(string phoneNumber, string last4Digits, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.veneka.com/Indigo/ICardRequest/GetCardListbyContactNumberExt", ReplyAction="http://schemas.veneka.com/Indigo/ICardRequest/GetCardListbyContactNumberExtRespon" +
            "se")]
        Indigo.CardReq.Response GetCardListbyContactNumberExt(string phoneNumber, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.veneka.com/Indigo/ICardRequest/GetCardListbyContactNumberExt", ReplyAction="http://schemas.veneka.com/Indigo/ICardRequest/GetCardListbyContactNumberExtRespon" +
            "se")]
        System.Threading.Tasks.Task<Indigo.CardReq.Response> GetCardListbyContactNumberExtAsync(string phoneNumber, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.veneka.com/Indigo/ICardRequest/GetCardsByPrepaidAccount", ReplyAction="http://schemas.veneka.com/Indigo/ICardRequest/GetCardsByPrepaidAccountResponse")]
        Indigo.CardReq.Response GetCardsByPrepaidAccount(string lastFourDigits, string prepaidAccountNumber, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.veneka.com/Indigo/ICardRequest/GetCardsByPrepaidAccount", ReplyAction="http://schemas.veneka.com/Indigo/ICardRequest/GetCardsByPrepaidAccountResponse")]
        System.Threading.Tasks.Task<Indigo.CardReq.Response> GetCardsByPrepaidAccountAsync(string lastFourDigits, string prepaidAccountNumber, string token);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICardRequestChannel : Indigo.CardReq.ICardRequest, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CardRequestClient : System.ServiceModel.ClientBase<Indigo.CardReq.ICardRequest>, Indigo.CardReq.ICardRequest {
        
        public CardRequestClient() {
        }
        
        public CardRequestClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CardRequestClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CardRequestClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CardRequestClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Indigo.CardReq.Response RequestCard(Indigo.CardReq.Request request) {
            return base.Channel.RequestCard(request);
        }
        
        public System.Threading.Tasks.Task<Indigo.CardReq.Response> RequestCardAsync(Indigo.CardReq.Request request) {
            return base.Channel.RequestCardAsync(request);
        }
        
        public Indigo.CardReq.Response RequestCardExt(Indigo.CardReq.Request request) {
            return base.Channel.RequestCardExt(request);
        }
        
        public System.Threading.Tasks.Task<Indigo.CardReq.Response> RequestCardExtAsync(Indigo.CardReq.Request request) {
            return base.Channel.RequestCardExtAsync(request);
        }
        
        public Indigo.CardReq.Response RequestedCardStatus(string referenceNumber) {
            return base.Channel.RequestedCardStatus(referenceNumber);
        }
        
        public System.Threading.Tasks.Task<Indigo.CardReq.Response> RequestedCardStatusAsync(string referenceNumber) {
            return base.Channel.RequestedCardStatusAsync(referenceNumber);
        }
        
        public Indigo.CardReq.Response QueryCardRequest(string referenceNumber) {
            return base.Channel.QueryCardRequest(referenceNumber);
        }
        
        public System.Threading.Tasks.Task<Indigo.CardReq.Response> QueryCardRequestAsync(string referenceNumber) {
            return base.Channel.QueryCardRequestAsync(referenceNumber);
        }
        
        public Indigo.CardReq.Response ActivateCard(string referenceNumber) {
            return base.Channel.ActivateCard(referenceNumber);
        }
        
        public System.Threading.Tasks.Task<Indigo.CardReq.Response> ActivateCardAsync(string referenceNumber) {
            return base.Channel.ActivateCardAsync(referenceNumber);
        }
        
        public Indigo.CardReq.Response ChangeCardStatus(string cardReferenceNumber, Indigo.CardReq.CardStatus newStatus) {
            return base.Channel.ChangeCardStatus(cardReferenceNumber, newStatus);
        }
        
        public System.Threading.Tasks.Task<Indigo.CardReq.Response> ChangeCardStatusAsync(string cardReferenceNumber, Indigo.CardReq.CardStatus newStatus) {
            return base.Channel.ChangeCardStatusAsync(cardReferenceNumber, newStatus);
        }
        
        public Indigo.CardReq.CardManagementResponse VerifyPersonByID(string AWBRefNumber, string IDNumber) {
            return base.Channel.VerifyPersonByID(AWBRefNumber, IDNumber);
        }
        
        public System.Threading.Tasks.Task<Indigo.CardReq.CardManagementResponse> VerifyPersonByIDAsync(string AWBRefNumber, string IDNumber) {
            return base.Channel.VerifyPersonByIDAsync(AWBRefNumber, IDNumber);
        }
        
        public Indigo.CardReq.CardManagementResponse QueryCardByAWBNumber(string AWBRefNumber) {
            return base.Channel.QueryCardByAWBNumber(AWBRefNumber);
        }
        
        public System.Threading.Tasks.Task<Indigo.CardReq.CardManagementResponse> QueryCardByAWBNumberAsync(string AWBRefNumber) {
            return base.Channel.QueryCardByAWBNumberAsync(AWBRefNumber);
        }
        
        public Indigo.CardReq.Response GetCardbyContactNumber(string phoneNumber, string token) {
            return base.Channel.GetCardbyContactNumber(phoneNumber, token);
        }
        
        public System.Threading.Tasks.Task<Indigo.CardReq.Response> GetCardbyContactNumberAsync(string phoneNumber, string token) {
            return base.Channel.GetCardbyContactNumberAsync(phoneNumber, token);
        }
        
        public Indigo.CardReq.Response GetCardbyContactNumberExt(string phoneNumber, string last4Digits, string token) {
            return base.Channel.GetCardbyContactNumberExt(phoneNumber, last4Digits, token);
        }
        
        public System.Threading.Tasks.Task<Indigo.CardReq.Response> GetCardbyContactNumberExtAsync(string phoneNumber, string last4Digits, string token) {
            return base.Channel.GetCardbyContactNumberExtAsync(phoneNumber, last4Digits, token);
        }
        
        public Indigo.CardReq.Response GetCardListbyContactNumberExt(string phoneNumber, string token) {
            return base.Channel.GetCardListbyContactNumberExt(phoneNumber, token);
        }
        
        public System.Threading.Tasks.Task<Indigo.CardReq.Response> GetCardListbyContactNumberExtAsync(string phoneNumber, string token) {
            return base.Channel.GetCardListbyContactNumberExtAsync(phoneNumber, token);
        }
        
        public Indigo.CardReq.Response GetCardsByPrepaidAccount(string lastFourDigits, string prepaidAccountNumber, string token) {
            return base.Channel.GetCardsByPrepaidAccount(lastFourDigits, prepaidAccountNumber, token);
        }
        
        public System.Threading.Tasks.Task<Indigo.CardReq.Response> GetCardsByPrepaidAccountAsync(string lastFourDigits, string prepaidAccountNumber, string token) {
            return base.Channel.GetCardsByPrepaidAccountAsync(lastFourDigits, prepaidAccountNumber, token);
        }
    }
}
